---
abstract: 'Export the Augeas tree to various formats'
author:
  - 'Raphaël Pinson <raphink@cpan.org>'
build_requires:
  File::Path: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
keywords:
  - augeas
  - export
  - configuration
  - 'configuration management'
  - xml
  - yaml
  - json
  - object
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Augeas-Exporter
provides:
  Config::Augeas::Exporter:
    file: lib/Config/Augeas/Exporter.pm
    version: v1.0.0
requires:
  Class::Accessor: 0
  Config::Augeas: 0
  Encode: 0
  File::Path: 0
  JSON: 0
  XML::LibXML: 0
  YAML: 0
resources:
  license: http://opensource.org/licenses/lgpl-license.php
  repository: https://code.launchpad.net/config-augeas-exporter
version: v1.0.0
