---
name: Config-Augeas-Exporter
version: v0.2.0
author: []
abstract: Export the Augeas tree to various formats
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
build_requires:
  Test::More: 0
requires:
  Class::Accessor: 0
  Config::Augeas: 0
  Encode: 0
  JSON: 0
  XML::LibXML: 0
  YAML: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Config::Augeas::Exporter:
    file: lib/Config/Augeas/Exporter.pm
    version: v0.2.0
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
