---
abstract: 'Export the Augeas tree to various formats'
author: []
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: LGPL
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Augeas-Exporter
provides:
  Config::Augeas::Exporter:
    file: lib/Config/Augeas/Exporter.pm
    version: 0.1
requires:
  Config::Augeas: 0
version: 0.1
