---
name: Config-Augeas-Exporter
version: 0.4
author:
  - 'Raphaël Pinson <raphink@cpan.org>'
abstract: Export the Augeas tree to various formats
license: lgpl
resources:
  license: http://opensource.org/licenses/lgpl-license.php
  repository: https://code.launchpad.net/config-augeas-exporter
build_requires:
  File::Path: 0
  Test::More: 0
requires:
  Class::Accessor: 0
  Config::Augeas: 0
  Encode: 0
  JSON: 0
  XML::LibXML: 0
  YAML: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Config::Augeas::Exporter:
    file: lib/Config/Augeas/Exporter.pm
    version: 0.4
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
keywords:
  - augeas
  - export
  - configuration
  - configuration management
  - xml
  - yaml
  - json
  - object
